name: Trigger auto deployment for metion-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/metion-backend-AutoDeployTrigger-eaeeb21e-a9de-4f09-9ef5-31f898cd29a4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.METIONBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.METIONBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.METIONBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}docker/Dockerfile.backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: metion.azurecr.io
          registryUsername: ${{ secrets.METIONBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.METIONBACKEND_REGISTRY_PASSWORD }}
          containerAppName: metion-backend
          resourceGroup: sandbox-aus
          imageToBuild: metion.azurecr.io/metion-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


